Implement capacity restrictions with regard to a maximal amount of containers that are allowed to run in parallel
MathGrass/mathgrass-server pull request #8
Opened 2023-04-01 13:01 UTC by tcq1

Closes #7 (partially)

2023-04-06 10:06 UTC, andreasdomanowski requested changes
Sehr schöne Arbeit! Nur Failed bei mir der Test de.tudresden.inf.st.mathgrass.api.task.execution.TaskExecutionManagerTest#testCreateTaskResult
> _expected: <8> but was: <7>_

Ansonsten ist die Frage, wann der EventBus mit den dynamischen Evaluationen zusammengeschraubt wird. Momentan wird in `de.tudresden.inf.st.mathgrass.api.task.execution.TaskExecutionManager#makeAssessment` so wie vorher blockierend an die Evaluation delegiert. Willst du das mit den WebSockets dann zusammen implementieren?

2023-04-06 10:06 UTC, andreasdomanowski commented on src/test/java/de/tudresden/inf/st/mathgrass/api/task/execution/TaskExecutionManagerTest.java
> +        assertEquals(taskSpy.getId(), taskResult.getTask().getId());
Failed bei mir lokal. Ansonsten sehr schicke Tests!

2023-04-07 23:13 UTC, tcq1 commented on src/test/java/de/tudresden/inf/st/mathgrass/api/task/execution/TaskExecutionManagerTest.java
> +        assertEquals(taskSpy.getId(), taskResult.getTask().getId());
Test ist gefixed, irgendwie ganz komischer Fehler. TaskResult wird Task mit richtiger ID übergeben, beim Laden des Tasks (in createTaskResult()) wird Task nochmal aus task repository geholt. Da wird nach Task mit ID 8 angefragt, es kommt als Ergebnis Task mit ID 7 zurück. Hab noch einiges rumprobiert aber keine Ahnung woher der Fehler kommt. Habe als Workaround die setup Methode angepasst, sodass sie nicht vor jedem Test läuft sondern nur ein mal vor allen Tests, sodass alle Tests mit der gleichen Instanz von Task arbeiten.

EventBus wollte ich mit dem WebSocketController erst einfügen, wollte den REST Endpunkt erstmal so belassen.

2023-04-12 14:31 UTC, andreasdomanowski approved these changes

2023-04-12 14:32 UTC, merged